name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  install-cardano-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the install script for a cardano node
        run: yes | src/install_latest_node.sh